openapi: 3.0.0
servers:
  - description: heroku deployment
    url: https://shrouded-fjord-98511.herokuapp.com/
  - description: local deployment
    url: http://localhost:8080
info:
  description: API to integrate with Google's calendar service
  version: "0.0.1"
  title: Calendar Integration Service
tags:
  - name: meta
    description: APIs related to OAuth2, configuration, and setup
  - name: cis
    description: APIs related to calendar integration service
paths:
  /echo:
    get:
      tags:
        - meta
      summary: repeats back what you send with the current time stamp
      operationId: echo
      description: >-
        By passing some value in the query string, this will send back the same
        data along with the current time. Useful for testing readiness and
        liveness.
      parameters:
        - in: query
          name: value
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
      responses:
        '200':
          description: returned data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /authorize:
    post:
      tags:
        - meta
      summary: set up new oauth access
      operationId: newAuthorization
      description: >-
        This API will return a URI to Google to complete access authorization.
      responses:
        '200':
          description: A new authorization object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAuthorizationResponse'

  /authorize/google:
    get:
      tags:
        - meta
      summary: presents API tokens after successful Google OAuth response
      operationId: googleOauthCallback
      parameters:
        - in: query
          name: code
          schema:
            type: string
        - in: query
          name: state
          schema:
            type: string
      responses:
        '200':
          description: A new access token object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAccessTokenResponse'

  /event:
    put:
      tags:
        - cis
      summary: update an existing event
      security:
        - bearerAuth: []
      operationId: updateEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Resulting event
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

  /event/list:
    get:
      tags:
        - cis
      summary: lists events for given date range (or today)
      security:
        - bearerAuth: []
      operationId: listEvents
      parameters:
        - in: query
          name: start
          description: local ISO date/date time, defaults to start of today
          schema:
            type: string
            format: date
        - in: query
          name: end
          description: local ISO date/date time, defaults to end of today
          schema:
            type: string
            format: date
        - in: query
          name: timezone
          description: specifies timezone for events, defaults to UTC
          schema:
            type: string
            example: America/Los_Angeles
        - in: query
          name: nextToken
          description: token pointing to next page of results
          schema:
            type: string
      responses:
        '200':
          description: Paginated list of calendar events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListEvents'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'

components:
  schemas:
    EchoResponse:
      type: object
      properties:
        value:
          type: string
          example: 'Hello, world!'
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'

    NewAuthorizationResponse:
      type: object
      properties:
        googleOauthUri:
          type: string
          format: uri

    NewAccessTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          format: uuid

    Event:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        location:
          type: string
        description:
          type: string
        startTime:
          type: string
          format: date-time
        endTime:
          type: string
          format: date-time
        internalAttendeesOnly:
          type: boolean
        attendees:
          type: array
          items:
            type: string
            format: email

    ListEvents:
      type: object
      properties:
        nextToken:
          type: string
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'

    ApiError:
      type: object
      properties:
        error:
          type: string
        requestId:
          type: string


  responses:
    BadRequestError:
      description: Missing or invalid request
    UnauthorizedError:
      description: Access token is missing or invalid
