openapi: 3.0.0
servers:
  - description: Local deployment
    url: http://localhost:5000
info:
  description: API to integrate with Google's calendar service
  version: "0.0.1"
  title: Calendar Integration Service
paths:
  /echo:
    get:
      summary: repeats back what you send with the current time stamp
      operationId: echo
      description: >-
        By passing some value in the query string, this will send back the same
        data along with the current time. Useful for testing readiness and
        liveness.
      parameters:
        - in: query
          name: value
          description: pass an optional search string for looking up inventory
          required: false
          schema:
            type: string
      responses:
        '200':
          description: returned data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EchoResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'

  /authorize:
    post:
      summary: set up new oauth access
      operationId: newAuthorization
      description: >-
        This API will return a URI to Google to complete access authorization.
      responses:
        '200':
          description: A new authorization object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAuthorizationResponse'

  /authorize/google:
    get:
      summary: presents API tokens after successful Google OAuth response
      operationId: googleOauthCallback
      parameters:
        - in: query
          name: code
          schema:
            type: string
        - in: query
          name: state
          schema:
            type: string
      responses:
        '200':
          description: A new access token object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewAccessTokenResponse'

  /events:
    get:
      security:
        - bearerAuth: []
      summary: lists
      operationId: nextEvents
      responses:
        '200':
          description: A new access token object
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NextEvents'

components:
  schemas:
    EchoResponse:
      type: object
      properties:
        value:
          type: string
          example: 'Hello, world!'
        timestamp:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'

    NewAuthorizationResponse:
      type: object
      properties:
        googleOauthUri:
          type: string
          format: uri

    NewAccessTokenResponse:
      type: object
      properties:
        accessToken:
          type: string
          format: uuid

    Event:
      type: object
      properties:
        title:
          type: string
        date:
          type: string
          format: date-time

    NextEvents:
      type: array
      items:
        $ref: '#/components/schemas/Event'


  responses:
    BadRequestError:
      description: Missing or invalid request
    UnauthorizedError:
      description: Access token is missing or invalid
